[variables]
COMPOSER_ALLOW_SUPERUSER = "1"

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-scripts --ignore-platform-reqs"]

[phases.build]
cmds = [
    "php bin/console importmap:install",
    "php bin/console assets:install",
    "php bin/console cache:clear --no-warmup"
]
