<?php

namespace App\DataFixtures;

use App\Entity\Category;
use App\Entity\Feature;
use App\Entity\Tag;
use App\Entity\Term;
use App\Enum\Difficulty;
use App\Enum\FeatureType;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;

class FeatureFixtures extends Fixture implements DependentFixtureInterface
{
    public function getDependencies(): array
    {
        return [TagFixtures::class, CategoryFixtures::class, TermFixtures::class];
    }

    public function load(ObjectManager $manager): void
    {
        foreach ($this->getFeatures() as $data) {
            $feature = new Feature();
            $feature->setName($data['name']);
            $feature->setSlug($data['slug']);
            $feature->setDescription($data['description']);
            $feature->setDifficulty($data['difficulty']);
            $feature->setType($data['type']);
            $feature->setSinceVersion($data['since'] ?? null);
            $feature->setCategory($this->getReference('cat-' . $data['category'], Category::class));

            foreach ($data['tags'] ?? [] as $tagSlug) {
                $feature->addTag($this->getReference('tag-' . $tagSlug, Tag::class));
            }
            foreach ($data['terms'] ?? [] as $termSlug) {
                if ($this->hasReference('term-' . $termSlug, Term::class)) {
                    $feature->addTerm($this->getReference('term-' . $termSlug, Term::class));
                }
            }

            $manager->persist($feature);
            $this->addReference('feature-' . $data['slug'], $feature);
        }

        $manager->flush();
    }

    private function getFeatures(): array
    {
        return [

            // ─── ROUTING ──────────────────────────────────────────────────────────────
            [
                'name' => 'Attribut #[Route]',
                'slug' => 'route-attribute',
                'category' => 'routing',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'since' => '6.0',
                'tags' => ['attribute', 'best-practice'],
                'terms' => [],
                'description' => 'Déclare une route directement sur une méthode de contrôleur via l\'attribut PHP #[Route]. Remplace les annotations Doctrine. Supporte les paramètres name, path, methods, requirements, defaults, host, schemes, condition, priority.',
            ],
            [
                'name' => '#[Route] sur la classe (préfixe)',
                'slug' => 'route-class-prefix',
                'category' => 'routing',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'since' => '6.0',
                'tags' => ['attribute', 'best-practice'],
                'terms' => [],
                'description' => 'Placer #[Route(\'/prefix\')] sur la classe du contrôleur préfixe automatiquement toutes les routes des méthodes de cette classe. Pratique pour les ressources CRUD.',
            ],
            [
                'name' => 'Requirements de routes (regex)',
                'slug' => 'route-requirements',
                'category' => 'routing',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Concept,
                'since' => '2.0',
                'tags' => [],
                'terms' => [],
                'description' => 'Les requirements contraignent les valeurs des paramètres de route via des expressions régulières. Ex: requirements: [\'id\' => \'\\d+\']. Symfony propose des constantes prêtes à l\'emploi : Requirement::DIGITS, ASCII_SLUG, etc.',
            ],
            [
                'name' => 'Valeurs par défaut de routes',
                'slug' => 'route-defaults',
                'category' => 'routing',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => [],
                'description' => 'Les defaults permettent de définir des valeurs par défaut pour les paramètres optionnels d\'une route ou d\'injecter des variables dans le contrôleur (ex: _format, _locale).',
            ],
            [
                'name' => 'Priorité de routes',
                'slug' => 'route-priority',
                'category' => 'routing',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => [],
                'description' => 'Le paramètre priority de #[Route] permet de définir l\'ordre d\'évaluation des routes. Plus la valeur est haute, plus la route est évaluée en premier. Utile quand deux routes peuvent correspondre à un même URL.',
            ],
            [
                'name' => 'Alias de routes',
                'slug' => 'route-alias',
                'category' => 'routing',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'since' => '6.1',
                'tags' => [],
                'terms' => [],
                'description' => 'Les alias de routes permettent de référencer une route sous plusieurs noms. Utile lors de renommages progressifs pour maintenir la compatibilité des URLs générées.',
            ],
            [
                'name' => 'Condition de route (expression)',
                'slug' => 'route-condition',
                'category' => 'routing',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => [],
                'description' => 'Le paramètre condition accepte une expression ExpressionLanguage évaluée à l\'exécution. Accès à request, env et context. Ex: condition: "request.headers.get(\'Accept\') matches \'/json/\'".',
            ],
            [
                'name' => 'Routage par sous-domaine',
                'slug' => 'subdomain-routing',
                'category' => 'routing',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => [],
                'description' => 'Le paramètre host de #[Route] permet de restreindre une route à un sous-domaine spécifique. Les variables du host peuvent être capturées comme paramètres de route.',
            ],
            [
                'name' => '#[MapQueryParameter]',
                'slug' => 'map-query-parameter',
                'category' => 'routing',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'since' => '6.3',
                'tags' => ['attribute', 'new-in-7', 'dx'],
                'terms' => [],
                'description' => 'Injecte et type-cast automatiquement un paramètre de query string dans un argument de contrôleur. Gère la validation de type et les tableaux. Ex: #[MapQueryParameter] int $page.',
            ],
            [
                'name' => '#[MapRequestPayload]',
                'slug' => 'map-request-payload',
                'category' => 'routing',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'since' => '6.3',
                'tags' => ['attribute', 'new-in-7', 'dx'],
                'terms' => [],
                'description' => 'Désérialise et valide automatiquement le corps d\'une requête JSON/form dans un DTO typé. Si la validation échoue, une 422 est retournée automatiquement.',
            ],
            [
                'name' => '#[MapEntity]',
                'slug' => 'map-entity',
                'category' => 'routing',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'since' => '6.2',
                'tags' => ['attribute', 'dx'],
                'terms' => [],
                'description' => 'Remplace @ParamConverter. Résout automatiquement une entité Doctrine depuis les paramètres de route. Supporte les expressions et le mapping de champs personnalisés.',
            ],
            [
                'name' => 'Génération d\'URL (UrlGenerator)',
                'slug' => 'url-generator',
                'category' => 'routing',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'tags' => ['best-practice'],
                'terms' => [],
                'description' => 'Le service router (UrlGeneratorInterface) génère des URLs depuis un nom de route et ses paramètres. generateUrl() en contrôleur, path()/url() en Twig. Supporte les URLs absolues et relatives.',
            ],
            [
                'name' => 'debug:router',
                'slug' => 'debug-router',
                'category' => 'routing',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Command,
                'tags' => ['console', 'dx'],
                'terms' => [],
                'description' => 'Commande console qui liste toutes les routes de l\'application avec leurs méthodes, chemins, contrôleurs. Supporte la recherche par nom et l\'affichage détaillé d\'une route.',
            ],

            // ─── DEPENDENCY INJECTION ─────────────────────────────────────────────────
            [
                'name' => 'Autowiring',
                'slug' => 'autowiring',
                'category' => 'di',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Concept,
                'tags' => ['best-practice', 'di'],
                'terms' => ['autowiring'],
                'description' => 'Le conteneur injecte automatiquement les dépendances en analysant les type-hints du constructeur. Actif par défaut (autowire: true dans services.yaml). Fonctionne avec interfaces si un seul service les implémente.',
            ],
            [
                'name' => 'Autoconfiguration',
                'slug' => 'autoconfiguration',
                'category' => 'di',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Concept,
                'tags' => ['best-practice', 'di'],
                'terms' => ['autoconfiguration'],
                'description' => 'Le conteneur détecte automatiquement les interfaces connues (EventSubscriberInterface, CommandInterface...) et applique les tags correspondants sans configuration manuelle.',
            ],
            [
                'name' => '#[Autowire]',
                'slug' => 'autowire-attribute',
                'category' => 'di',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Attribute,
                'since' => '6.1',
                'tags' => ['attribute', 'di', 'dx'],
                'terms' => ['autowiring'],
                'description' => 'Précise explicitement ce qu\'injecter pour un paramètre : service, paramètre de conteneur, expression ou valeur d\'env. Ex: #[Autowire(\'%app.secret%\')] ou #[Autowire(service: \'monservice\')].',
            ],
            [
                'name' => '#[AutowireDecorated]',
                'slug' => 'autowire-decorated',
                'category' => 'di',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Attribute,
                'since' => '6.1',
                'tags' => ['attribute', 'di'],
                'terms' => ['autowiring'],
                'description' => 'Injecte automatiquement le service décoré dans un décorateur. Évite de déclarer manuellement le service inner. Utilisé avec le pattern Decorator.',
            ],
            [
                'name' => '#[AutoconfigureTag]',
                'slug' => 'autoconfigure-tag',
                'category' => 'di',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Attribute,
                'since' => '6.1',
                'tags' => ['attribute', 'di'],
                'terms' => ['service-tag', 'autoconfiguration'],
                'description' => 'Applique automatiquement un tag à tous les services d\'une interface ou classe abstraite. Évite de configurer le tag dans services.yaml pour chaque implémentation.',
            ],
            [
                'name' => '#[Target]',
                'slug' => 'target-attribute',
                'category' => 'di',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Attribute,
                'since' => '6.2',
                'tags' => ['attribute', 'di'],
                'terms' => ['autowiring'],
                'description' => 'Désambiguïse l\'autowiring lorsque plusieurs services implémentent la même interface. #[Target(\'mailerLogger\')] indique lequel des LoggerInterface injecter.',
            ],
            [
                'name' => '#[When] (environnement)',
                'slug' => 'when-attribute',
                'category' => 'di',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Attribute,
                'since' => '6.2',
                'tags' => ['attribute', 'di', 'config'],
                'terms' => [],
                'description' => 'Enregistre un service uniquement dans certains environnements. #[When(env: \'dev\')] ou #[When(env: \'test\')] évite les conditions dans services.yaml.',
            ],
            [
                'name' => 'Service Locator',
                'slug' => 'service-locator',
                'category' => 'di',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => ['di', 'performance'],
                'terms' => ['service-locator'],
                'description' => 'Conteneur léger injectant un sous-ensemble de services de façon lazy. Utile dans les factories ou handlers qui n\'ont besoin que d\'un service à la fois parmi plusieurs.',
            ],
            [
                'name' => 'Services lazys',
                'slug' => 'lazy-services',
                'category' => 'di',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => ['di', 'performance'],
                'terms' => ['lazy-service'],
                'description' => 'Un service marqué lazy: true est instancié via un proxy uniquement au premier appel effectif. Réduit le temps de bootstrap pour les services coûteux non toujours utilisés.',
            ],
            [
                'name' => 'Binding de paramètres',
                'slug' => 'binding',
                'category' => 'di',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Configuration,
                'tags' => ['di', 'config'],
                'terms' => [],
                'description' => 'La clé bind dans services.yaml mappe une valeur (paramètre, service) à un nom d\'argument ou type. Pratique pour injecter la même valeur dans tous les services sans répétition.',
            ],
            [
                'name' => 'Compiler Pass',
                'slug' => 'compiler-pass',
                'category' => 'di',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => ['di'],
                'terms' => ['compiler-pass'],
                'description' => 'Classe ModifiantContainerBuilder pendant la compilation. Utilisation typique : collecter des services par tag et les injecter dans un service central (ex: collecte des handlers, extensions Twig).',
            ],
            [
                'name' => 'Décorateur de service',
                'slug' => 'service-decorator',
                'category' => 'di',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => ['di', 'best-practice'],
                'terms' => [],
                'description' => 'Pattern permettant d\'encapsuler un service existant sans modifier son code. Configurer avec decorates: dans services.yaml ou l\'attribut #[AsDecorator]. Le service décoré est injecté via #[AutowireDecorated].',
            ],
            [
                'name' => 'debug:container',
                'slug' => 'debug-container',
                'category' => 'di',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Command,
                'tags' => ['console', 'di', 'dx'],
                'terms' => [],
                'description' => 'Liste tous les services du conteneur. Options utiles : --show-private, --tag=twig.extension, --type=LoggerInterface. Indispensable pour debugger l\'autowiring.',
            ],

            // ─── HTTP FOUNDATION ──────────────────────────────────────────────────────
            [
                'name' => 'Objet Request',
                'slug' => 'request-object',
                'category' => 'http-foundation',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'tags' => ['http'],
                'terms' => [],
                'description' => 'Encapsule la requête HTTP. Donne accès à query ($request->query), POST ($request->request), fichiers ($request->files), headers ($request->headers), cookies, session, attributs, méthode, URL, format attendu.',
            ],
            [
                'name' => 'Objet Response',
                'slug' => 'response-object',
                'category' => 'http-foundation',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'tags' => ['http'],
                'terms' => [],
                'description' => 'Représente la réponse HTTP renvoyée au client. Contient le statut HTTP, les headers, le body. Sous-classes : JsonResponse, RedirectResponse, BinaryFileResponse, StreamedResponse.',
            ],
            [
                'name' => 'JsonResponse',
                'slug' => 'json-response',
                'category' => 'http-foundation',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'tags' => ['http', 'best-practice'],
                'terms' => [],
                'description' => 'Réponse HTTP qui sérialise automatiquement un tableau ou objet PHP en JSON et positionne le header Content-Type: application/json. Méthode raccourci $this->json() dans AbstractController.',
            ],
            [
                'name' => 'Session',
                'slug' => 'session',
                'category' => 'http-foundation',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'tags' => ['http'],
                'terms' => [],
                'description' => 'Gestion des sessions HTTP. RequestStack::getSession() retourne la session courante. Supports : PHP natif, PDO, Redis, Memcached. Flash messages via addFlash() / getFlashBag().',
            ],
            [
                'name' => '#[MapQueryString]',
                'slug' => 'map-query-string',
                'category' => 'http-foundation',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'since' => '7.1',
                'tags' => ['attribute', 'new-in-7', 'dx'],
                'terms' => [],
                'description' => 'Mappe toute la query string vers un objet DTO typé en un seul paramètre de contrôleur. Inclut validation automatique. Variante de #[MapRequestPayload] pour les GET.',
            ],
            [
                'name' => 'File Upload',
                'slug' => 'file-upload',
                'category' => 'http-foundation',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'tags' => ['http'],
                'terms' => [],
                'description' => 'Les fichiers uploadés sont accessibles via $request->files, retournant des instances de UploadedFile. Méthodes move(), guessExtension(), getMimeType(), isValid().',
            ],
            [
                'name' => 'BinaryFileResponse',
                'slug' => 'binary-file-response',
                'category' => 'http-foundation',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'tags' => ['http', 'performance'],
                'terms' => [],
                'description' => 'Envoie un fichier au client avec support des headers Range (téléchargement partiel), Content-Disposition, Cache-Control. sendfile() kernel optionnel pour X-Accel-Redirect (Nginx).',
            ],

            // ─── HTTP KERNEL ──────────────────────────────────────────────────────────
            [
                'name' => 'Cycle de vie du Kernel',
                'slug' => 'kernel-lifecycle',
                'category' => 'http-kernel',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => ['http'],
                'terms' => ['kernel'],
                'description' => 'handle(Request) déclenche la séquence : kernel.request → kernel.controller → kernel.controller_arguments → contrôleur → kernel.view → kernel.response → kernel.terminate. Chaque étape est un événement interceptable.',
            ],
            [
                'name' => 'Événements Kernel',
                'slug' => 'kernel-events',
                'category' => 'http-kernel',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => ['http'],
                'terms' => ['event-dispatcher'],
                'description' => 'KernelEvents::REQUEST, CONTROLLER, CONTROLLER_ARGUMENTS, VIEW, RESPONSE, FINISH_REQUEST, EXCEPTION, TERMINATE. Permettent d\'intercepter et modifier la requête ou la réponse à chaque étape.',
            ],
            [
                'name' => 'Argument Resolver',
                'slug' => 'argument-resolver',
                'category' => 'http-kernel',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => ['di', 'dx'],
                'terms' => [],
                'description' => 'Résout les arguments d\'un contrôleur avant son appel. Des resolvers built-in gèrent Request, services, entités (#[MapEntity]), payload (#[MapRequestPayload])... Extensible via ValueResolverInterface.',
            ],
            [
                'name' => 'Sous-requêtes',
                'slug' => 'sub-requests',
                'category' => 'http-kernel',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => ['http'],
                'terms' => ['kernel'],
                'description' => 'HttpKernelInterface::handle() peut être appelé récursivement avec SUB_REQUEST pour inclure le résultat d\'un autre contrôleur dans la réponse. Utilisé par l\'ESI et render() Twig.',
            ],

            // ─── SECURITY ─────────────────────────────────────────────────────────────
            [
                'name' => 'Firewall',
                'slug' => 'firewall',
                'category' => 'security',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Configuration,
                'tags' => ['security', 'config'],
                'terms' => ['firewall'],
                'description' => 'Zone de sécurité définie dans security.yaml. Chaque firewall a son pattern d\'URL, ses authenticateurs, son provider d\'utilisateurs et sa configuration de session. Ex: firewalls.api (stateless JWT) + firewalls.main.',
            ],
            [
                'name' => 'Authenticator',
                'slug' => 'authenticator',
                'category' => 'security',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Component,
                'since' => '5.3',
                'tags' => ['security'],
                'terms' => ['authenticator', 'security-passport'],
                'description' => 'Remplace les Guard Authenticators. Implémente AuthenticatorInterface : supports(), authenticate() → Passport, onAuthenticationSuccess(), onAuthenticationFailure(). Plus modulaire grâce aux Badges.',
            ],
            [
                'name' => 'Security Passport & Badges',
                'slug' => 'passport-badges',
                'category' => 'security',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'since' => '5.3',
                'tags' => ['security'],
                'terms' => ['security-passport'],
                'description' => 'Un Passport contient les credentials (UserBadge + PasswordCredentials ou SelfValidatingPassport) et des badges optionnels : CsrfTokenBadge, RememberMeBadge, PasswordUpgradeBadge.',
            ],
            [
                'name' => 'Voter',
                'slug' => 'voter',
                'category' => 'security',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'tags' => ['security', 'best-practice'],
                'terms' => ['voter'],
                'description' => 'Centralise la logique d\'autorisation pour une ressource. Hérite de Voter<TAttribute, TSubject>. voteOnAttribute() retourne true/false. Déclenché via $this->denyAccessUnlessGranted() ou #[IsGranted].',
            ],
            [
                'name' => '#[IsGranted]',
                'slug' => 'is-granted-attribute',
                'category' => 'security',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'since' => '6.0',
                'tags' => ['attribute', 'security'],
                'terms' => ['voter'],
                'description' => 'Attribut sur un contrôleur ou méthode déclarant l\'autorisation requise. Lève une AccessDeniedException si la condition n\'est pas remplie. Ex: #[IsGranted(\'ROLE_ADMIN\')] ou #[IsGranted(\'edit\', \'post\')].',
            ],
            [
                'name' => 'Access Control (security.yaml)',
                'slug' => 'access-control',
                'category' => 'security',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Configuration,
                'tags' => ['security', 'config'],
                'terms' => [],
                'description' => 'Liste de règles dans security.yaml matchant des patterns d\'URL. Chaque règle peut exiger un rôle, une IP, un canal (HTTPS) ou une expression. Évaluées dans l\'ordre, la première qui match est appliquée.',
            ],
            [
                'name' => 'Hiérarchie de rôles',
                'slug' => 'role-hierarchy',
                'category' => 'security',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Configuration,
                'tags' => ['security'],
                'terms' => [],
                'description' => 'role_hierarchy dans security.yaml définit quels rôles héritent d\'autres rôles. Ex: ROLE_ADMIN: [ROLE_USER]. Un utilisateur ROLE_ADMIN possède automatiquement ROLE_USER.',
            ],
            [
                'name' => 'Password Hasher',
                'slug' => 'password-hasher',
                'category' => 'security',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'tags' => ['security', 'best-practice'],
                'terms' => [],
                'description' => 'UserPasswordHasherInterface hash les mots de passe selon l\'algorithme configuré (bcrypt, argon2id, sodium). hashPassword() + isPasswordValid(). Supporte le rehashage automatique (needsRehash()).',
            ],
            [
                'name' => 'CSRF Protection',
                'slug' => 'csrf-protection',
                'category' => 'security',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'tags' => ['security'],
                'terms' => ['csrf-token'],
                'description' => 'CsrfTokenManagerInterface génère et valide des tokens anti-CSRF. Intégré automatiquement dans les Form Symfony. Pour les routes custom, utiliser isCsrfTokenValid() dans le contrôleur.',
            ],
            [
                'name' => 'Remember Me',
                'slug' => 'remember-me',
                'category' => 'security',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'tags' => ['security'],
                'terms' => [],
                'description' => 'Fonctionnalité "se souvenir de moi" via un cookie persistant. Activé par RememberMeBadge dans le Passport. Configurable dans le firewall : lifetime, secure, samesite.',
            ],
            [
                'name' => 'Expression Language dans la sécurité',
                'slug' => 'security-expression',
                'category' => 'security',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => ['security'],
                'terms' => [],
                'description' => 'Les expressions permettent des règles d\'autorisation complexes. Dans #[IsGranted] ou access_control: is_granted(\'ROLE\') and request.isSecure(). Accès à user, object, token, trust_resolver.',
            ],

            // ─── CONSOLE ──────────────────────────────────────────────────────────────
            [
                'name' => '#[AsCommand]',
                'slug' => 'as-command',
                'category' => 'console',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'since' => '6.0',
                'tags' => ['attribute', 'console', 'best-practice'],
                'terms' => [],
                'description' => 'Déclare une classe comme commande console. name définit la commande, description la description courte, aliases les alias, hidden masque de la liste. Remplace la méthode configure() pour ces métadonnées.',
            ],
            [
                'name' => 'Arguments et Options',
                'slug' => 'command-args-options',
                'category' => 'console',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Concept,
                'tags' => ['console'],
                'terms' => [],
                'description' => 'addArgument() définit des arguments positionnels (obligatoires ou optionnels). addOption() définit des options (--name=value ou --flag). InputArgument et InputOption avec modes : REQUIRED, OPTIONAL, IS_ARRAY.',
            ],
            [
                'name' => 'SymfonyStyle (io)',
                'slug' => 'symfony-style',
                'category' => 'console',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'tags' => ['console', 'dx'],
                'terms' => ['symfony-style'],
                'description' => 'SymfonyStyle($input, $output) offre title(), section(), text(), note(), caution(), success(), error(), table(), listing(), ask(), confirm(), progressStart(). Sortie stylisée et cohérente.',
            ],
            [
                'name' => 'Table Helper',
                'slug' => 'table-helper',
                'category' => 'console',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'tags' => ['console'],
                'terms' => [],
                'description' => 'Affiche des données tabulaires dans le terminal. new Table($output) → setHeaders() → addRows() → render(). Styles : default, compact, borderless, box, box-double.',
            ],
            [
                'name' => 'Progress Bar',
                'slug' => 'progress-bar',
                'category' => 'console',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'tags' => ['console'],
                'terms' => [],
                'description' => 'ProgressBar($output, $max) affiche une barre de progression. start() → advance() → finish(). Personnalisable via setFormat() et setBarCharacter(). SymfonyStyle::progressStart() pour usage simplifié.',
            ],
            [
                'name' => 'Commandes lazys',
                'slug' => 'lazy-commands',
                'category' => 'console',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => ['console', 'performance'],
                'terms' => [],
                'description' => 'Avec #[AsCommand], les commandes sont enregistrées en mode lazy : l\'objet n\'est instancié que lorsqu\'elle est effectivement appelée. Améliore significativement le temps de démarrage des grosses applications.',
            ],
            [
                'name' => 'Événements de commande',
                'slug' => 'command-events',
                'category' => 'console',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => ['console'],
                'terms' => ['event-dispatcher'],
                'description' => 'ConsoleEvents::COMMAND (avant exécution), ConsoleEvents::TERMINATE (après succès), ConsoleEvents::ERROR (sur exception). Permettent de logger, auditer ou modifier le comportement des commandes.',
            ],
            [
                'name' => 'make:command',
                'slug' => 'make-command',
                'category' => 'console',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Command,
                'tags' => ['console', 'dx'],
                'terms' => [],
                'description' => 'Génère le squelette d\'une nouvelle commande console avec #[AsCommand], configure() et execute() pré-remplis. Fait partie du MakerBundle.',
            ],

            // ─── FORMS ────────────────────────────────────────────────────────────────
            [
                'name' => 'Form Type',
                'slug' => 'form-type',
                'category' => 'forms',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'tags' => [],
                'terms' => ['form-type'],
                'description' => 'Classe héritant de AbstractType définissant un formulaire. buildForm() ajoute les champs, configureOptions() définit data_class, validation_groups, etc. Réutilisable et composable.',
            ],
            [
                'name' => 'Types de champs built-in',
                'slug' => 'form-field-types',
                'category' => 'forms',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => [],
                'description' => 'TextType, EmailType, PasswordType, IntegerType, NumberType, CheckboxType, ChoiceType, EntityType, DateType, DateTimeType, FileType, HiddenType, CollectionType, RepeatedType, SubmitType...',
            ],
            [
                'name' => 'Validation de formulaire',
                'slug' => 'form-validation',
                'category' => 'forms',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => ['best-practice'],
                'terms' => ['constraint'],
                'description' => 'Les contraintes Validator appliquées sur le data_class sont vérifiées lors de isValid(). Groupes de validation via validation_groups. Contraintes directement sur les champs via constraints: option.',
            ],
            [
                'name' => 'Data Transformer',
                'slug' => 'data-transformer',
                'category' => 'forms',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => ['data-transformer'],
                'description' => 'Convertit entre la vue (ex: string "Paris") et le modèle (ex: objet City). Deux types : Model Transformers (modèle ↔ normalisé) et View Transformers (normalisé ↔ vue HTML).',
            ],
            [
                'name' => 'Form Events',
                'slug' => 'form-events',
                'category' => 'forms',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => ['event-dispatcher'],
                'description' => 'FormEvents::PRE_SET_DATA, POST_SET_DATA, PRE_SUBMIT, SUBMIT, POST_SUBMIT permettent de modifier dynamiquement la structure du formulaire selon les données (ex: champs conditionnels).',
            ],
            [
                'name' => 'CollectionType',
                'slug' => 'collection-type',
                'category' => 'forms',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Component,
                'tags' => [],
                'terms' => [],
                'description' => 'Gère une collection de sous-formulaires. allow_add / allow_delete permettent d\'ajouter/supprimer dynamiquement des éléments en JS. Utilisé avec prototype pour le template JS.',
            ],

            // ─── DOCTRINE ORM ─────────────────────────────────────────────────────────
            [
                'name' => 'Mapping d\'entité par attributs',
                'slug' => 'entity-attributes',
                'category' => 'doctrine',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'tags' => ['attribute', 'best-practice'],
                'terms' => ['entity'],
                'description' => '#[ORM\\Entity], #[ORM\\Column], #[ORM\\Id], #[ORM\\GeneratedValue], #[ORM\\ManyToOne], #[ORM\\OneToMany], #[ORM\\ManyToMany], #[ORM\\JoinColumn]. Remplace le XML/YAML depuis Doctrine 2.9.',
            ],
            [
                'name' => 'Relations Doctrine',
                'slug' => 'doctrine-relations',
                'category' => 'doctrine',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => ['entity', 'repository'],
                'description' => 'OneToOne, OneToMany/ManyToOne, ManyToMany. Chaque relation a un côté owning (JoinColumn/JoinTable) et un côté inverse (mappedBy/inversedBy). Le côté owning est celui persisté.',
            ],
            [
                'name' => 'Repository et QueryBuilder',
                'slug' => 'doctrine-querybuilder',
                'category' => 'doctrine',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'tags' => [],
                'terms' => ['repository', 'querybuilder'],
                'description' => 'ServiceEntityRepository fournit find(), findBy(), findOneBy(). createQueryBuilder() retourne un QueryBuilder fluent pour des requêtes complexes avec jointures, conditions, tri, pagination.',
            ],
            [
                'name' => 'Migrations Doctrine',
                'slug' => 'doctrine-migrations',
                'category' => 'doctrine',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Command,
                'tags' => ['best-practice'],
                'terms' => ['migration'],
                'description' => 'doctrine:migrations:diff génère la migration depuis le diff schéma/entités. doctrine:migrations:migrate l\'applique. Chaque migration a up() et down(). Versionnée en base dans la table doctrine_migration_versions.',
            ],
            [
                'name' => 'Lifecycle Callbacks',
                'slug' => 'lifecycle-callbacks',
                'category' => 'doctrine',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Attribute,
                'tags' => ['attribute'],
                'terms' => ['entity'],
                'description' => '#[ORM\\PrePersist], #[ORM\\PostPersist], #[ORM\\PreUpdate], #[ORM\\PostUpdate], #[ORM\\PreRemove], #[ORM\\PostRemove], #[ORM\\PostLoad]. Méthodes de l\'entité appelées automatiquement par Doctrine.',
            ],
            [
                'name' => 'Embeddables',
                'slug' => 'doctrine-embeddables',
                'category' => 'doctrine',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => [],
                'description' => '#[ORM\\Embeddable] et #[ORM\\Embedded] permettent d\'intégrer un objet value-object dans une entité. Les colonnes de l\'embeddable sont ajoutées à la table de l\'entité parente avec un préfixe.',
            ],
            [
                'name' => 'Héritage de mapping',
                'slug' => 'doctrine-inheritance',
                'category' => 'doctrine',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => [],
                'description' => 'Trois stratégies : SINGLE_TABLE (discriminator column, une table), JOINED (une table par classe, JOINs), TABLE_PER_CLASS (une table complète par classe). Configuré via #[ORM\\InheritanceType] et #[ORM\\DiscriminatorMap].',
            ],
            [
                'name' => 'DQL',
                'slug' => 'dql',
                'category' => 'doctrine',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => ['dql'],
                'description' => 'Doctrine Query Language : langage de requête orienté entités. SELECT u FROM App\\Entity\\User u WHERE u.email = :email. Supporte JOIN, GROUP BY, HAVING, sous-requêtes. Compilé en SQL selon le driver.',
            ],

            // ─── SERIALIZER ───────────────────────────────────────────────────────────
            [
                'name' => 'Groupes de sérialisation',
                'slug' => 'serializer-groups',
                'category' => 'serializer',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => ['normalizer'],
                'description' => '#[Groups([\'read\', \'write\'])] sur les propriétés. Passer les groupes dans le contexte du serializer ou de l\'ApiResource. Permet d\'exposer différentes propriétés selon le contexte (lecture, écriture, sous-ressource).',
            ],
            [
                'name' => '#[SerializedName]',
                'slug' => 'serialized-name',
                'category' => 'serializer',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'tags' => ['attribute'],
                'terms' => ['normalizer'],
                'description' => 'Définit le nom utilisé dans la représentation sérialisée indépendamment du nom de la propriété PHP. Ex: #[SerializedName(\'firstName\')] sur une propriété $first_name.',
            ],
            [
                'name' => '#[MaxDepth]',
                'slug' => 'max-depth',
                'category' => 'serializer',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Attribute,
                'tags' => ['attribute', 'performance'],
                'terms' => ['normalizer'],
                'description' => 'Limite la profondeur de sérialisation des relations circulaires ou profondes. Nécessite l\'activation de ENABLE_MAX_DEPTH dans le contexte. Évite les boucles infinies sans configuration lourde.',
            ],
            [
                'name' => 'Normalizer personnalisé',
                'slug' => 'custom-normalizer',
                'category' => 'serializer',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Component,
                'tags' => [],
                'terms' => ['normalizer'],
                'description' => 'Implémenter NormalizerInterface / DenormalizerInterface pour gérer la sérialisation d\'un type spécifique. supportsNormalization() décide si le normalizer prend en charge un objet donné.',
            ],
            [
                'name' => '#[SerializedPath]',
                'slug' => 'serialized-path',
                'category' => 'serializer',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Attribute,
                'since' => '6.3',
                'tags' => ['attribute', 'new-in-7'],
                'terms' => ['normalizer'],
                'description' => 'Mappe une propriété PHP à un chemin imbriqué dans la structure JSON/XML. Ex: #[SerializedPath(\'[data][user][name]\')] pour accéder à data.user.name depuis une propriété $name.',
            ],

            // ─── VALIDATOR ────────────────────────────────────────────────────────────
            [
                'name' => 'Contraintes built-in',
                'slug' => 'built-in-constraints',
                'category' => 'validator',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => ['constraint'],
                'description' => 'NotBlank, NotNull, Length, Email, Url, Regex, Range, Choice, Count, UniqueEntity, Valid, All, Collection, Type, IsTrue, IsFalse, Positive, Negative, Uuid, Iban, Bic, Isbn, Issn, Cidr, Hostname...',
            ],
            [
                'name' => 'Contrainte personnalisée',
                'slug' => 'custom-constraint',
                'category' => 'validator',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => ['constraint', 'constraint-validator'],
                'description' => 'Créer une classe Constraint (avec message) et un ConstraintValidator (avec validate()). Utiliser $this->context->buildViolation()->addViolation() pour signaler une erreur.',
            ],
            [
                'name' => 'Groupes de validation',
                'slug' => 'validation-groups',
                'category' => 'validator',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => ['constraint'],
                'description' => 'Les contraintes peuvent être assignées à des groupes. validator->validate($object, null, [\'creation\']) n\'exécute que les contraintes du groupe "creation". GroupSequence permet un ordre strict.',
            ],
            [
                'name' => 'Contrainte Sequentially',
                'slug' => 'sequentially-constraint',
                'category' => 'validator',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'since' => '6.1',
                'tags' => [],
                'terms' => ['constraint'],
                'description' => 'Exécute des contraintes l\'une après l\'autre et s\'arrête à la première violation. Évite des messages d\'erreur multiples et redondants (ex: vérifier NotBlank avant Email).',
            ],
            [
                'name' => 'Contrainte Compound',
                'slug' => 'compound-constraint',
                'category' => 'validator',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'since' => '6.1',
                'tags' => ['new-in-7'],
                'terms' => ['constraint'],
                'description' => 'Regroupe plusieurs contraintes en une seule contrainte réutilisable. Hériter de Compound et implémenter getConstraints(). Ex: #[PasswordStrength] = NotBlank + Length(min:8) + Regex.',
            ],

            // ─── EVENT DISPATCHER ─────────────────────────────────────────────────────
            [
                'name' => '#[AsEventListener]',
                'slug' => 'as-event-listener',
                'category' => 'event-dispatcher',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'since' => '6.0',
                'tags' => ['attribute', 'best-practice'],
                'terms' => ['event-dispatcher'],
                'description' => 'Enregistre une méthode comme listener d\'événement sans implémenter d\'interface. #[AsEventListener(event: KernelEvents::REQUEST, method: \'onRequest\', priority: 10)].',
            ],
            [
                'name' => 'Event Subscriber',
                'slug' => 'event-subscriber',
                'category' => 'event-dispatcher',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => ['event-dispatcher', 'autoconfiguration'],
                'description' => 'Implémenter EventSubscriberInterface avec getSubscribedEvents() retournant un tableau events → méthodes. Auto-configuré par le conteneur. Préférer #[AsEventListener] pour les nouveaux projets.',
            ],
            [
                'name' => 'Événements stoppables',
                'slug' => 'stoppable-events',
                'category' => 'event-dispatcher',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => ['event-dispatcher'],
                'description' => 'Un événement implémentant StoppableEventInterface peut être stoppé via stopPropagation(). Les listeners suivants ne sont pas appelés. isPropagationStopped() permet de vérifier l\'état.',
            ],

            // ─── CACHE ────────────────────────────────────────────────────────────────
            [
                'name' => 'Cache Pools',
                'slug' => 'cache-pools',
                'category' => 'cache',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => ['performance'],
                'terms' => ['cache-pool'],
                'description' => 'Pools nommés configurés dans cache.yaml. Adaptateurs : filesystem, redis, memcached, apcu, array, pdo. Chaque pool a son namespace et TTL par défaut. CacheInterface ou PSR-16 CacheInterface.',
            ],
            [
                'name' => 'Cache Tags (invalidation)',
                'slug' => 'cache-tags',
                'category' => 'cache',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => ['performance'],
                'terms' => ['cache-tag'],
                'description' => 'TagAwareCacheInterface permet de tagger des items et de les invalider par tag. Exemple : invalider tous les items tagués "user-42" quand un utilisateur est modifié. Adaptateurs supportés : Redis, Memcached, filesystem.',
            ],
            [
                'name' => '#[Cache] (HTTP caching)',
                'slug' => 'http-cache-attribute',
                'category' => 'cache',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Attribute,
                'since' => '7.1',
                'tags' => ['attribute', 'performance', 'http', 'new-in-7'],
                'terms' => [],
                'description' => 'Attribut sur un contrôleur configurant les headers HTTP Cache-Control, Expires, ETag, Last-Modified. Intégration avec le composant HttpCache (reverse proxy PHP) ou Varnish via ESI.',
            ],
            [
                'name' => 'Cache Warmer',
                'slug' => 'cache-warmer',
                'category' => 'cache',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => ['performance'],
                'terms' => [],
                'description' => 'Implémente CacheWarmerInterface pour pré-remplir le cache lors de cache:warmup. Appelé par symfony cache:warmup. isOptional() indique si le warmup peut être ignoré.',
            ],

            // ─── MAILER ───────────────────────────────────────────────────────────────
            [
                'name' => 'Envoyer un email',
                'slug' => 'send-email',
                'category' => 'mailer',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'tags' => [],
                'terms' => [],
                'description' => 'MailerInterface::send(Email $email). Email() → from() → to() → subject() → text() → html(). Transport configuré via MAILER_DSN : smtp://, gmail+smtp://, sendgrid+api://, null://, in-memory://',
            ],
            [
                'name' => 'Email basé sur Twig',
                'slug' => 'twig-email',
                'category' => 'mailer',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'tags' => ['best-practice'],
                'terms' => [],
                'description' => 'TemplatedEmail() → htmlTemplate() / textTemplate() utilise Twig pour le corps de l\'email. Inlining CSS automatique avec Twig Inky. Pièces jointes via attachFromPath() ou embed().',
            ],
            [
                'name' => 'Mailer asynchrone',
                'slug' => 'async-mailer',
                'category' => 'mailer',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => ['async', 'performance'],
                'terms' => ['transport', 'message-bus'],
                'description' => 'En configurant Messenger, les emails sont envoyés de façon asynchrone. MAILER_DSN reste synchrone mais le transport Messenger délègue l\'envoi à un worker. Routing automatique via symfony/mailer.',
            ],

            // ─── MESSENGER ────────────────────────────────────────────────────────────
            [
                'name' => '#[AsMessageHandler]',
                'slug' => 'as-message-handler',
                'category' => 'messenger',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'since' => '6.0',
                'tags' => ['attribute', 'async', 'best-practice'],
                'terms' => ['message-bus', 'middleware'],
                'description' => 'Enregistre une classe ou méthode __invoke() comme handler d\'un message. Le type du paramètre de __invoke() détermine le message géré. Un handler peut gérer plusieurs types via plusieurs méthodes.',
            ],
            [
                'name' => 'Transports Messenger',
                'slug' => 'messenger-transports',
                'category' => 'messenger',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => ['async'],
                'terms' => ['transport'],
                'description' => 'AMQP (RabbitMQ), Redis Streams, Doctrine (table BDD), SQS (Amazon), Beanstalkd, In-Memory (sync). Configurés via DSN dans messenger.yaml. Chaque transport peut avoir son propre routing.',
            ],
            [
                'name' => 'Routing de messages',
                'slug' => 'messenger-routing',
                'category' => 'messenger',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Configuration,
                'tags' => ['async'],
                'terms' => ['transport', 'message-bus'],
                'description' => 'routing dans messenger.yaml mappe des classes de messages à des transports. Plusieurs transports possibles par message. Un message non routé est traité de façon synchrone.',
            ],
            [
                'name' => 'Retry Strategy',
                'slug' => 'messenger-retry',
                'category' => 'messenger',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Configuration,
                'tags' => ['async'],
                'terms' => ['stamp', 'envelope'],
                'description' => 'En cas d\'échec de traitement, Messenger réessaie le message selon la stratégie configurée (max_retries, delay, multiplier). Après épuisement, le message va dans le transport failure (failed queue).',
            ],
            [
                'name' => 'Stamps et Enveloppes',
                'slug' => 'stamps-envelopes',
                'category' => 'messenger',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => ['async'],
                'terms' => ['stamp', 'envelope'],
                'description' => 'bus->dispatch(new MyMessage(), [new DelayStamp(5000)]). Stamps disponibles : DelayStamp, TransportNamesStamp, ReceivedStamp, HandledStamp, SentStamp, RedeliveryStamp, AmqpStamp...',
            ],
            [
                'name' => 'Middleware Messenger',
                'slug' => 'messenger-middleware',
                'category' => 'messenger',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Concept,
                'tags' => ['async'],
                'terms' => ['middleware'],
                'description' => 'Couche interceptant chaque message avant/après dispatch. Built-in : SendMessageMiddleware, HandleMessageMiddleware, ValidationMiddleware, DoctrineTransactionMiddleware. Extensible via MiddlewareInterface.',
            ],
            [
                'name' => 'messenger:consume',
                'slug' => 'messenger-consume',
                'category' => 'messenger',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Command,
                'tags' => ['async', 'console'],
                'terms' => ['transport'],
                'description' => 'Lance un worker consommant les messages d\'un ou plusieurs transports. Options : --limit (nombre de messages), --time-limit (durée), --memory-limit, --sleep (attente entre messages). Supervisord recommandé en production.',
            ],

            // ─── TWIG ─────────────────────────────────────────────────────────────────
            [
                'name' => 'Héritage de templates',
                'slug' => 'twig-inheritance',
                'category' => 'twig',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Concept,
                'tags' => ['best-practice'],
                'terms' => [],
                'description' => '{% extends \'base.html.twig\' %} hérite d\'un template parent. {% block content %}{% endblock %} définit des zones remplaçables. {{ parent() }} inclut le contenu du bloc parent.',
            ],
            [
                'name' => 'Extension Twig',
                'slug' => 'twig-extension',
                'category' => 'twig',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'tags' => ['best-practice'],
                'terms' => ['service-tag', 'autoconfiguration'],
                'description' => 'Hériter de AbstractExtension pour ajouter des filtres (getFilters()), fonctions (getFunctions()), tests, opérateurs, globals et node visitors. Taggé automatiquement twig.extension via autoconfiguration.',
            ],
            [
                'name' => 'Fonctions et filtres Twig utiles',
                'slug' => 'twig-builtins',
                'category' => 'twig',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => [],
                'description' => 'Fonctions : path(), url(), asset(), is_granted(), csrf_token(), render(), include(), dump(). Filtres : |date, |trans, |format_currency, |format_number, |escape, |raw, |slice, |json_encode, |yaml_encode.',
            ],
            [
                'name' => 'Composants Twig (UX)',
                'slug' => 'twig-components',
                'category' => 'twig',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'since' => '7.0',
                'tags' => ['new-in-7', 'dx'],
                'terms' => [],
                'description' => '#[AsTwigComponent] marque une classe PHP comme composant Twig réutilisable. Props automatiquement mappées, template dans templates/components/. Live Components ajoutent l\'interactivité sans JS custom.',
            ],

            // ─── CONFIGURATION ────────────────────────────────────────────────────────
            [
                'name' => 'Variables d\'environnement',
                'slug' => 'env-vars',
                'category' => 'configuration',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Configuration,
                'tags' => ['config', 'best-practice', 'security'],
                'terms' => [],
                'description' => 'Déclarées dans .env, surchargées dans .env.local (non commité). Utilisées via %env(VAR)% dans les configs. Processeurs : env(int:PORT), env(bool:FLAG), env(json:DATA), env(base64:...), env(file:...).',
            ],
            [
                'name' => 'Secrets Symfony',
                'slug' => 'secrets',
                'category' => 'configuration',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Component,
                'since' => '4.4',
                'tags' => ['security', 'config'],
                'terms' => [],
                'description' => 'secrets:set chiffre une valeur et la stocke dans config/secrets/. En production, seule la clé publique est commitée. %env(secret:APP_SECRET)% déchiffre à l\'exécution. Vault externe possible.',
            ],
            [
                'name' => 'Config Component (TreeBuilder)',
                'slug' => 'config-tree-builder',
                'category' => 'configuration',
                'difficulty' => Difficulty::Advanced,
                'type' => FeatureType::Component,
                'tags' => ['config'],
                'terms' => [],
                'description' => 'Définit la structure de configuration d\'un bundle avec validation et normalisation automatiques. TreeBuilder avec scalarNode, arrayNode, booleanNode, integerNode, enumNode. Utilisé dans Configuration::getConfigTreeBuilder().',
            ],
            [
                'name' => 'PHP config (kernel.php)',
                'slug' => 'php-config',
                'category' => 'configuration',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Configuration,
                'since' => '5.3',
                'tags' => ['config', 'best-practice', 'dx'],
                'terms' => [],
                'description' => 'Les fichiers de configuration peuvent être écrits en PHP (config/packages/*.php). Syntaxe fluente avec $configurator->extension(). Autocomplétion IDE meilleure que YAML. Recommandé pour les nouveaux projets Symfony 8.',
            ],

            // ─── TESTING ──────────────────────────────────────────────────────────────
            [
                'name' => 'WebTestCase',
                'slug' => 'web-test-case',
                'category' => 'testing',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'tags' => ['test', 'best-practice'],
                'terms' => [],
                'description' => 'Classe de base pour les tests fonctionnels HTTP. createClient() retourne un Client simulant un navigateur. $client->request(\'GET\', \'/\'), $client->submitForm(), $crawler->filter(). Vérifie les réponses HTTP.',
            ],
            [
                'name' => 'KernelTestCase',
                'slug' => 'kernel-test-case',
                'category' => 'testing',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'tags' => ['test'],
                'terms' => ['kernel'],
                'description' => 'Charge le kernel Symfony sans serveur HTTP. self::getContainer() donne accès aux services. Utilisé pour tester des services, repositories, commandes sans couche HTTP.',
            ],
            [
                'name' => 'Mocking de services en test',
                'slug' => 'mock-services',
                'category' => 'testing',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => ['test'],
                'terms' => [],
                'description' => 'self::getContainer()->set(MyService::class, $mock) remplace un service dans le conteneur de test. Combiné avec createMock() de PHPUnit. Pratique pour mocker les appels externes (API, Mailer, HttpClient).',
            ],
            [
                'name' => 'MockHttpClient',
                'slug' => 'mock-http-client',
                'category' => 'testing',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'tags' => ['test', 'http'],
                'terms' => ['http-client'],
                'description' => 'MockHttpClient + MockResponse simule des réponses HTTP sans appel réseau. Pratique pour tester les services qui appellent des APIs externes. Vérification des requêtes envoyées via MockResponse::getRequestOptions().',
            ],
            [
                'name' => 'Crawler (DomCrawler)',
                'slug' => 'dom-crawler',
                'category' => 'testing',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'tags' => ['test'],
                'terms' => [],
                'description' => 'API de traversal HTML/XML dans les tests fonctionnels. filter(\'h1\'), filterXPath(), text(), attr(), link(), form(). Permet de vérifier le contenu HTML des réponses et de naviguer dans les pages.',
            ],

            // ─── ASSET MAPPER ─────────────────────────────────────────────────────────
            [
                'name' => 'AssetMapper',
                'slug' => 'asset-mapper',
                'category' => 'asset-mapper',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Component,
                'since' => '6.3',
                'tags' => ['new-in-7', 'best-practice'],
                'terms' => ['importmap'],
                'description' => 'Gestion des assets front-end sans webpack/npm. Les fichiers JS/CSS dans assets/ sont servis directement avec versioning par hash. Supporte les ES modules natifs et l\'importmap.',
            ],
            [
                'name' => 'Importmap',
                'slug' => 'importmap',
                'category' => 'asset-mapper',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Concept,
                'since' => '6.3',
                'tags' => ['new-in-7'],
                'terms' => ['importmap'],
                'description' => 'importmap.php liste les packages JS et leurs CDN URLs (jsDelivr). importmap:require ajoute un package. {{ importmap(\'app\') }} dans Twig injecte le script approprié. Compatible navigateurs modernes.',
            ],
            [
                'name' => 'importmap:require',
                'slug' => 'importmap-require',
                'category' => 'asset-mapper',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Command,
                'since' => '6.3',
                'tags' => ['console', 'new-in-7'],
                'terms' => ['importmap'],
                'description' => 'Ajoute un package npm à l\'importmap via jsDelivr ou unpkg. Ex: symfony importmap:require bootstrap. Met à jour importmap.php automatiquement. Pas de node_modules nécessaire.',
            ],

            // ─── SCHEDULER ────────────────────────────────────────────────────────────
            [
                'name' => '#[AsPeriodicTask]',
                'slug' => 'as-periodic-task',
                'category' => 'scheduler',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'since' => '6.3',
                'tags' => ['attribute', 'async', 'new-in-7'],
                'terms' => [],
                'description' => 'Planifie l\'exécution périodique d\'un message Messenger. #[AsPeriodicTask(frequency: \'1 hour\', from: \'now\')] sur un handler. S\'exécute via messenger:consume scheduler.',
            ],
            [
                'name' => '#[AsCronTask]',
                'slug' => 'as-cron-task',
                'category' => 'scheduler',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Attribute,
                'since' => '6.3',
                'tags' => ['attribute', 'async', 'new-in-7'],
                'terms' => [],
                'description' => 'Planifie une tâche via une expression cron. #[AsCronTask(\'0 * * * *\')] pour toutes les heures. Supporte les timezones. Plus expressif que #[AsPeriodicTask] pour des planifications complexes.',
            ],

            // ─── WORKFLOW ─────────────────────────────────────────────────────────────
            [
                'name' => 'Workflow vs StateMachine',
                'slug' => 'workflow-vs-statemachine',
                'category' => 'workflow',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => ['place', 'transition', 'marking-store'],
                'description' => 'Workflow : un objet peut être dans plusieurs places simultanément (Petri net). StateMachine : une seule place à la fois. Configurés dans workflow.yaml. StateMachine est un cas particulier de Workflow.',
            ],
            [
                'name' => 'Guards de Workflow',
                'slug' => 'workflow-guards',
                'category' => 'workflow',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => ['transition', 'voter'],
                'description' => 'Listeners sur WorkflowEvents::GUARD_[TRANSITION] permettant de bloquer une transition dynamiquement. $event->setBlocked(true, \'raison\'). Vérification des droits, données, état externe.',
            ],
            [
                'name' => 'Événements Workflow',
                'slug' => 'workflow-events',
                'category' => 'workflow',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => ['transition', 'place', 'event-dispatcher'],
                'description' => 'workflow.[name].guard.[transition], workflow.[name].leave.[place], workflow.[name].transition.[transition], workflow.[name].enter.[place], workflow.[name].announce.[transition].',
            ],

            // ─── TRANSLATION ──────────────────────────────────────────────────────────
            [
                'name' => 'Catalogues de traduction',
                'slug' => 'translation-catalogs',
                'category' => 'translation',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => [],
                'description' => 'Fichiers YAML/XLIFF dans translations/. Nommés [domaine].[locale].yaml (ex: messages.fr.yaml). $translator->trans(\'key\', [], \'domain\', \'fr\'). Hiérarchie de fallback locale.',
            ],
            [
                'name' => 'Format ICU',
                'slug' => 'icu-format',
                'category' => 'translation',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'tags' => [],
                'terms' => [],
                'description' => 'Format de message internationalisé standard. Support de la pluralisation {count, plural, one{# item} other{# items}}, des genres, des sélections. Actif via le format +intl-icu dans le nom de fichier.',
            ],
            [
                'name' => 'Extraction automatique (translation:extract)',
                'slug' => 'translation-extract',
                'category' => 'translation',
                'difficulty' => Difficulty::Beginner,
                'type' => FeatureType::Command,
                'tags' => ['console', 'dx'],
                'terms' => [],
                'description' => 'translation:extract --force fr analyse le code source et les templates Twig pour extraire les clés de traduction et les ajouter aux fichiers de catalogue manquants.',
            ],

            // ─── RATE LIMITER ─────────────────────────────────────────────────────────
            [
                'name' => 'Politiques de Rate Limiting',
                'slug' => 'rate-limiter-policies',
                'category' => 'rate-limiter',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Concept,
                'since' => '5.2',
                'tags' => ['security', 'performance'],
                'terms' => [],
                'description' => 'Quatre stratégies : token_bucket (tokens rechargés progressivement), fixed_window (N req/période fixe), sliding_window (fenêtre glissante), no_limit. Configuré dans rate_limiter.yaml.',
            ],
            [
                'name' => '#[RateLimit]',
                'slug' => 'rate-limit-attribute',
                'category' => 'rate-limiter',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Attribute,
                'since' => '7.2',
                'tags' => ['attribute', 'security', 'new-in-7', 'new-in-8'],
                'terms' => [],
                'description' => 'Attribut sur un contrôleur limitant le débit directement sans code dans l\'action. #[RateLimit(policy: \'api\', limit: 60, interval: \'1 minute\')] → 429 automatique si dépassé.',
            ],

            // ─── LOCK ─────────────────────────────────────────────────────────────────
            [
                'name' => 'Lock Factory',
                'slug' => 'lock-factory',
                'category' => 'lock',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'since' => '3.4',
                'tags' => ['async'],
                'terms' => [],
                'description' => 'LockFactory::createLock(\'resource-name\', ttl) crée un verrou. acquire() → release(). Stores : Redis, Semaphore (Unix), Flock (fichier), PDO, ZooKeeper, MongoDB. Verrous partagés (read) et exclusifs (write).',
            ],

            // ─── CLOCK ────────────────────────────────────────────────────────────────
            [
                'name' => 'ClockInterface',
                'slug' => 'clock-interface',
                'category' => 'clock',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'since' => '6.2',
                'tags' => ['new-in-7', 'test', 'best-practice'],
                'terms' => [],
                'description' => 'Abstraction du temps système. now() retourne un DateTimeImmutable. Implémentations : NativeClock (temps réel), MockClock (temps figé pour tests), MonotonicClock (temps monotone). Injecter ClockInterface plutôt que new DateTime().',
            ],
            [
                'name' => 'MockClock (tests)',
                'slug' => 'mock-clock',
                'category' => 'clock',
                'difficulty' => Difficulty::Intermediate,
                'type' => FeatureType::Component,
                'since' => '6.2',
                'tags' => ['test', 'new-in-7'],
                'terms' => [],
                'description' => 'MockClock permet de figer ou manipuler le temps dans les tests. sleep() ou modify(\'+1 day\') avance le temps. Élimine les tests flaky liés au temps réel.',
            ],
        ];
    }
}
